workflows:
    react-native:
        name: React Native App Android
        environment:
            vars:
                XCODE_WORKSPACE: "exploreApp"
                XCODE_SCHEME: "exploreApp"
            node: latest
        scripts:
            - npm install
            - echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android/local.properties"
            - |
                # build Android
                cd android
                ./gradlew assembleDebug
        artifacts:
            - android/app/build/outputs/**/**/*.apk
        publishing: 
          email:
            recipients:
              - ahmadfathonizumaro@gmail.com
              - toniebe48@gmail.com
            notify:
              success: true
              failure: false