export const dataCallPlan = [
    {
      MobileCallID: "MC123456",
      PlanID: 101,
      AppID: 201,
      DatePlan: new Date("2024-10-01"),
      PosStructureID: 301,
      DoctorID: 401,
      DoctorTypeID: 1,
      DoctorType: "Specialist",
      AliasName: "Dr. Smith",
      DoctorSegment: 2,
      DoctorSector: 3,
      PotensiValue: 500,
      StatusPlan: 1,
      IsActivePlan: true,
      ApprovalNotes: "Urgent approval needed",
      TypePlan: "Routine",
      ApproveID: 1011,
      RejectID: null,
      IsActiveResult: 1,
      LastUpdate: new Date("2024-10-10"),
      saveType: 1,
      PICCode: "PC001",
      PICID: 501,
      PICName: "Jane Doe",
      PICType: 2,
      CodeDoctor: "DOC001",
      DoctorName: "Dr. John Smith",
      ActivityProgramID: 601,
      IsActivityProgram: 1,
    },
    {
      MobileCallID: "MC123457",
      PlanID: 102,
      AppID: 202,
      DatePlan: new Date("2024-10-02"),
      PosStructureID: 302,
      DoctorID: 402,
      DoctorTypeID: 2,
      DoctorType: "General",
      AliasName: "Dr. Adams",
      DoctorSegment: 1,
      DoctorSector: 2,
      PotensiValue: 300,
      StatusPlan: 2,
      IsActivePlan: false,
      ApprovalNotes: "Pending review",
      TypePlan: "Follow-up",
      ApproveID: null,
      RejectID: 1021,
      IsActiveResult: 0,
      LastUpdate: new Date("2024-10-11"),
      saveType: 2,
      PICCode: "PC002",
      PICID: 502,
      PICName: "John Doe",
      PICType: 1,
      CodeDoctor: "DOC002",
      DoctorName: "Dr. Emily Adams",
      ActivityProgramID: null,
      IsActivityProgram: 0,
    },
    {
      MobileCallID: "MC123458",
      PlanID: 103,
      AppID: 203,
      DatePlan: new Date("2024-10-03"),
      PosStructureID: 303,
      DoctorID: 403,
      DoctorTypeID: 3,
      DoctorType: "Surgeon",
      AliasName: "Dr. Clark",
      DoctorSegment: 3,
      DoctorSector: 1,
      PotensiValue: 700,
      StatusPlan: 3,
      IsActivePlan: true,
      ApprovalNotes: "Approved",
      TypePlan: "Emergency",
      ApproveID: 1031,
      RejectID: null,
      IsActiveResult: 1,
      LastUpdate: new Date("2024-10-12"),
      saveType: 1,
      PICCode: "PC003",
      PICID: 503,
      PICName: "Alice Johnson",
      PICType: 3,
      CodeDoctor: "DOC003",
      DoctorName: "Dr. Mark Clark",
      ActivityProgramID: 602,
      IsActivityProgram: 1,
    },
    {
      MobileCallID: "MC123459",
      PlanID: 104,
      AppID: 204,
      DatePlan: new Date("2024-10-04"),
      PosStructureID: 304,
      DoctorID: 404,
      DoctorTypeID: null,
      DoctorType: null,
      AliasName: "Dr. Thomas",
      DoctorSegment: 2,
      DoctorSector: 3,
      PotensiValue: 450,
      StatusPlan: 0,
      IsActivePlan: false,
      ApprovalNotes: null,
      TypePlan: "Consultation",
      ApproveID: null,
      RejectID: null,
      IsActiveResult: 0,
      LastUpdate: new Date("2024-10-13"),
      saveType: 2,
      PICCode: "PC004",
      PICID: 504,
      PICName: "Robert Lee",
      PICType: 1,
      CodeDoctor: "DOC004",
      DoctorName: "Dr. Olivia Thomas",
      ActivityProgramID: null,
      IsActivityProgram: 0,
    },
    {
      MobileCallID: "MC123460",
      PlanID: 105,
      AppID: 205,
      DatePlan: new Date("2024-10-05"),
      PosStructureID: 305,
      DoctorID: 405,
      DoctorTypeID: 4,
      DoctorType: "Pediatrician",
      AliasName: "Dr. Hill",
      DoctorSegment: 1,
      DoctorSector: 2,
      PotensiValue: 600,
      StatusPlan: 1,
      IsActivePlan: true,
      ApprovalNotes: "For next quarter",
      TypePlan: "Routine",
      ApproveID: 1051,
      RejectID: null,
      IsActiveResult: 1,
      LastUpdate: new Date("2024-10-14"),
      saveType: 1,
      PICCode: "PC005",
      PICID: 505,
      PICName: "Linda Wong",
      PICType: 2,
      CodeDoctor: "DOC005",
      DoctorName: "Dr. Noah Hill",
      ActivityProgramID: 603,
      IsActivityProgram: 1,
    },
  ];
  