export const CallPlan = {
    name: "CallPlan",
    primaryKey: "MobileCallID",
    properties: {
      MobileCallID: "string",
      PlanID: "int?",
      AppID: "int?",
      DatePlan: "date",
      PosStructureID: "int",
      DoctorID: "int",
      DoctorTypeID: "int?",
      DoctorType: "string?",
      AliasName: "string?",
      DoctorSegment: "int",
      DoctorSector: "int",
      PotensiValue: "int",
      StatusPlan: "int",
      IsActivePlan: "bool",
      ApprovalNotes: "string?",
      TypePlan: "string",
      ApproveID: "int?",
      RejectID: "int?",
      IsActiveResult: "int?",
      LastUpdate: "date",
      saveType: "int",
      PICCode: "string?",
      PICID: "int?",
      PICName: "string?",
      PICType: "int?",
      CodeDoctor: "string?",
      DoctorName: "string?",
      ActivityProgramID: "int?",
      IsActivityProgram: "int?",
    }
  }
